mainsite/urls.py
from django.urls import path
from .views import (
    HomeView,
    SendSmsView,
    SmsResendView,
    PreviousSmsDetailsView,
    PreviousSmsListView,
    DevicesStatusView,
    ReassignDevicesView,
)

app_name = "mainsite"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("send_sms/", SendSmsView.as_view(), name="send_sms"),
    path(
        "prev_sms/<int:pk>/",
        PreviousSmsDetailsView.as_view(),
        name="prev_sms_status_details",
    ),
    path("prev_sms/", PreviousSmsListView.as_view(), name="prev_sms_status"),
    path("devices_status/", DevicesStatusView.as_view(), name="devices_status"),
    path("sms_resend/<int:pk>/", SmsResendView.as_view(), name="sms_resend"),
    path("reassign_devices/", ReassignDevicesView.as_view(), name="reassign_devices"),
]

mainsite/models.py
from django.db import models

# Create your models here.

mainsite/forms.py
from django import forms
from sms_send.models import SmsGroupMessage


class SendSmsForm(forms.ModelForm):
    """ Form to send a SMS """

    class Meta:
        model = SmsGroupMessage
        fields = ["recipients", "body"]
        labels = {"recipients": "Envoyer à", "body": "Message"}

mainsite/views.py
import itertools

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db.models import Max

from sms_send.models import (
    SmsMessage,
    SmsGroupMessage,
    SmsDevice,
    SmsRecipient,
    SmsRecipientGroup,
)
from .forms import SendSmsForm


class IsStaffMixin(PermissionRequiredMixin):
    permission_required = "is_staff"


class HomeView(IsStaffMixin, TemplateView):
    """ Home page """

    template_name = "mainsite/home.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["sms_sent"] = SmsMessage.objects.filter(sent_status="S").count()
        context["sms_errors"] = SmsMessage.objects.filter(sent_status="E").count()
        return context


class SendSmsView(IsStaffMixin, CreateView):
    """ Send a SMS """

    template_name = "mainsite/send_sms.html"

    model = SmsGroupMessage
    # fields = ["recipients", "body"]
    form_class = SendSmsForm

    def get_success_url(self):
        return reverse(
            "mainsite:prev_sms_status_details", kwargs={"pk": self.object.pk}
        )

    def form_valid(self, form):
        self.object = form.save()
        self.object.instanciate()
        self.object.send_all()
        return HttpResponseRedirect(self.get_success_url())


class SmsResendView(IsStaffMixin, SingleObjectMixin, RedirectView):
    model = SmsGroupMessage
    http_method_names = ["post"]

    def get_redirect_url(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.send_all()
        return reverse(
            "mainsite:prev_sms_status_details", kwargs={"pk": self.object.pk}
        )


class ReassignDevicesView(IsStaffMixin, RedirectView):
    http_method_names = ["post"]

    @staticmethod
    def round_robin(l_a, l_b):
        """ Iterates over the elements of a, with elements of b in a round-robin
        fashion.
        Eg. if l_a = [1, 2, 3, 4, 5], l_b = [1, 2], this will yield
        [(1,1), (2,2), (3,1), (4,2), (5,1)].
        """
        for (a, b) in itertools.zip_longest(l_a, itertools.cycle(l_b)):
            if a:  # After iterating over l_a, a will be None
                yield (a, b)
            else:
                break

    def get_redirect_url(self, *args, **kwargs):
        recipients = SmsRecipient.objects.all()
        devices = SmsDevice.objects.all()
        devices = list(filter(lambda x: x.is_available(), devices))
        if not devices:
            messages.error(
                self.request,
                (
                    "Impossible de réassigner les destinataires : "
                    + "aucun téléphone d'envoi disponible actuellement."
                ),
            )
        else:
            for (recipient, device) in self.round_robin(recipients, devices):
                recipient.last_sms_device = device
                recipient.save()
        return reverse("mainsite:devices_status")


class PreviousSmsDetailsView(IsStaffMixin, DetailView):
    model = SmsGroupMessage
    template_name = "mainsite/previous_sms_details.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["group_message"] = self.object
        context["individual_messages"] = self.object.individual_messages.all()
        return context


class PreviousSmsListView(IsStaffMixin, ListView):
    model = SmsGroupMessage
    template_name = "mainsite/previous_sms_list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related("individual_messages").annotate(
            max_date=Max("individual_messages__sent_date")
        )


class DevicesStatusView(IsStaffMixin, TemplateView):
    template_name = "mainsite/devices_status.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["devices"] = SmsDevice.objects.all().prefetch_related(
            "smsrecipient_set"
        )
        return context

mainsite/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <title>Traque — Envoi de SMS</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    {% block extra_head %}{% endblock %}
    {% if use_jquery %}<script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>{% endif %}
  </head>

  <body class="{% block page-class %}{% endblock %}">
    <header>
      <div class="header_upper_row">
        <h1><a href="{% url 'mainsite:home' %}">La Traque - SMS</a></h1>
        <div class="devices_availability devices_availability_{{ sms_devices_status }}">
          Tél. :
          {{ available_sms_devices_count }} / {{ sms_devices_count }} UP
        </div>
      </div>

      <nav>
        <ul id="navright">
          {% if user.username %}
            <li id="username">
              {{ user.username }}
            </li>
            <li id="logout">
              <a href="{% url "account_logout" %}">
                Déconnexion
              </a>
            </li>

          {% else %}
            <li id="login">
              <a href="{% url "account_login" %}">
                Connexion
              </a>
            </li>
          {% endif %}
        </ul>
        <ul id="navleft">
          <li>
            <a href="{% url 'mainsite:home' %}">Accueil</a>
          </li>

          <li>
            <a href="{% url 'mainsite:devices_status' %}">
              État des téléphones
            </a>
          </li>

          <li>
            <a href="{% url 'mainsite:send_sms' %}">Envoyer un SMS</a>
          </li>

          <li>
            <a href="{% url 'mainsite:prev_sms_status' %}">SMS envoyés</a>
          </li>

          {% if user.is_staff %}
          <li>
            <a href="{% url 'admin:index' %}">Administration</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <div id="container">
      <h1 id="pagename">
        {% block pagename %}{% endblock %}
      </h1>

      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="msg {% if message.tags %} {{ message.tags }}{% endif %}">
          {{ message }}
        </div>
        {% endfor %}
      </div>
      {% endif %}

      <div id="content">
      {% block content %}{% endblock %}
      </div>
    </div>

  </body>
</html>