mainsite/urls.py
from django.urls import path
from .views import (
    HomeView,
    SendSmsView,
    SmsResendView,
    PreviousSmsDetailsView,
    PreviousSmsListView,
    DevicesStatusView,
    ReassignDevicesView,
)

app_name = "mainsite"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("send_sms/", SendSmsView.as_view(), name="send_sms"),
    path(
        "prev_sms/<int:pk>/",
        PreviousSmsDetailsView.as_view(),
        name="prev_sms_status_details",
    ),
    path("prev_sms/", PreviousSmsListView.as_view(), name="prev_sms_status"),
    path("devices_status/", DevicesStatusView.as_view(), name="devices_status"),
    path("sms_resend/<int:pk>/", SmsResendView.as_view(), name="sms_resend"),
    path("reassign_devices/", ReassignDevicesView.as_view(), name="reassign_devices"),
]

mainsite/models.py
from django.db import models

# Create your models here.

sms_send/models.py
import logging
from django.db import models
from django.core import validators
from django.utils import timezone
from .maxs_util import MaxsDevice

logger = logging.getLogger(__name__)


class SmsDevice(models.Model):
    """ Physical device capable of sending SMSs """

    device_name = models.CharField(
        help_text="Human-readable device name", max_length=255
    )
    device_xmpp_account = models.CharField(
        unique=True, help_text="XMPP account used to control this phone", max_length=255
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.device_handler = MaxsDevice.get_instance(self.device_xmpp_account)

    def is_available(self):
        return self.device_handler.is_available()

    def __str__(self):
        return "{} <{}> ({})".format(
            self.device_name,
            self.device_xmpp_account,
            "UP" if self.is_available() else "DOWN",
        )


class SmsRecipient(models.Model):
    """ A recipient of SMS messages """

    last_sms_device = models.ForeignKey(
        SmsDevice,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        default=None,
        help_text="SMS device last used to send SMS to this recipient",
    )
    phone_number = models.CharField(
        validators=[validators.RegexValidator(regex=r"\+[0-9]+")],
        unique=True,
        max_length=20,
    )
    name = models.CharField(
        help_text="Human-readable name for this recipient", max_length=255
    )

    @property
    def device(self):
        """ Get this recipient's sending device """
        if self.last_sms_device and self.last_sms_device.is_available():
            return self.last_sms_device
        possible_devices = (
            SmsDevice.objects.all()
            .annotate(num_recipients=models.Count("smsrecipient"))
            .order_by("num_recipients")
        )
        for cur_device in possible_devices:
            if cur_device.is_available():
                self.last_sms_device = cur_device
                self.save()
                return cur_device
        return None

    def __str__(self):
        return "{} <{}>".format(self.name, self.phone_number)


class SmsRecipientGroup(models.Model):
    """ A group of recipients, possibly recursive """

    name = models.CharField(max_length=512, help_text="Human-readable label")
    individual_recipients = models.ManyToManyField(
        SmsRecipient,
        blank=True,
        related_name="group_memberships",
        help_text="Individual SmsRecipients belonging to this group",
    )
    group_recipients = models.ManyToManyField(
        "SmsRecipientGroup",
        blank=True,
        related_name="metagroups",
        help_text="Whole groups belonging to this group",
    )

    def all_recipients(self):
        """ Recursively aggregate individual recipients into a queryset """
        qs = self.individual_recipients.all()
        for group in self.group_recipients.all():
            qs = qs.union(group.all_recipients())
        return qs

    def __str__(self):
        return "{} ({} individuals, {} groups)".format(
            self.name, self.individual_recipients.count(), self.group_recipients.count()
        )


class SmsMessage(models.Model):
    SENT_STATUS_CHOICES = [
        ("N", "Never sent"),
        ("P", "Pending"),
        ("S", "Sent"),
        ("E", "Error while sending"),
    ]

    class AlreadySent(Exception):
        def __str__(self):
            return "This message has already been sent"

    recipient = models.ForeignKey(SmsRecipient, on_delete=models.CASCADE)
    body = models.TextField()
    sent_status = models.CharField(
        max_length=2, choices=SENT_STATUS_CHOICES, default="N"
    )
    sent_date = models.DateTimeField(
        null=True,
        default=None,
        help_text="Time and date at which this message was sent",
    )
    group_message = models.ForeignKey(
        "SmsGroupMessage",
        on_delete=models.CASCADE,
        related_name="individual_messages",
        null=True,
        blank=True,
        default=None,
        help_text="Group message this message is an instance of",
    )
    sending_device = models.ForeignKey(
        SmsDevice,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
        help_text="Device who sent — or tried to send — this message",
    )

    @classmethod
    def sent_status_to_text(cls, status):
        return dict(cls.SENT_STATUS_CHOICES)[status]

    @property
    def sent_status_text(self):
        return self.sent_status_to_text(self.sent_status)

    def __str__(self):
        return "To {}: {} [{}]".format(
            self.recipient.name, self.body[:20] + "…", self.sent_status_text
        )

    def send(self, bypass_already_sent=False):
        if not self.pk:
            raise Exception("This message must be saved first.")

        if not bypass_already_sent and self.sent_status in ["S", "P"]:
            raise self.AlreadySent()

        device = self.recipient.device
        if not device:
            self.update_status("E")
            logger.error("Cannot send {}: no available device".format(self.pk))
            return
        self.sending_device = device
        self.save()
        device.device_handler.send_sms(self.recipient.phone_number, self.body, self)
        self.update_status("P")

    def update_status(self, status):
        self.sent_status = status
        self.sent_date = timezone.now()
        self.save()

    def mark_sent(self):
        self.update_status("S")


class SmsGroupMessage(models.Model):
    recipients = models.ForeignKey(SmsRecipientGroup, on_delete=models.CASCADE)
    body = models.TextField()

    def instanciate(self):
        """ Create all the individual messages """
        if not self.pk:
            raise Exception("SmsGroupMessage must be saved before instanciating")
        for recipient in self.recipients.all_recipients():
            message = SmsMessage(
                recipient=recipient, body=self.body, group_message=self
            )
            message.save()

    @property
    def group_proeminent_status(self):
        if self.individual_messages.filter(sent_status="E").exists():
            return "E"
        elif self.individual_messages.filter(sent_status="P").exists():
            return "P"
        elif self.individual_messages.filter(sent_status="N").exists():
            return "N"
        return "S"

    @property
    def group_proeminent_status_text(self):
        return SmsMessage.sent_status_to_text(self.group_proeminent_status)

    @property
    def can_resend(self):
        return self.group_proeminent_status in ["E", "N", "P"]

    def send_all(self):
        for message in self.individual_messages.all():
            try:
                message.send()
            except SmsMessage.AlreadySent:
                # Ignore messages already sent to allow resending after errors occurred
                pass

mainsite/forms.py
from django import forms
from sms_send.models import SmsGroupMessage


class SendSmsForm(forms.ModelForm):
    """ Form to send a SMS """

    class Meta:
        model = SmsGroupMessage
        fields = ["recipients", "body"]
        labels = {"recipients": "Envoyer à", "body": "Message"}

mainsite/views.py
import itertools

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db.models import Max

from sms_send.models import (
    SmsMessage,
    SmsGroupMessage,
    SmsDevice,
    SmsRecipient,
    SmsRecipientGroup,
)
from .forms import SendSmsForm


class IsStaffMixin(PermissionRequiredMixin):
    permission_required = "is_staff"


class HomeView(IsStaffMixin, TemplateView):
    """ Home page """

    template_name = "mainsite/home.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["sms_sent"] = SmsMessage.objects.filter(sent_status="S").count()
        context["sms_errors"] = SmsMessage.objects.filter(sent_status="E").count()
        return context


class SendSmsView(IsStaffMixin, CreateView):
    """ Send a SMS """

    template_name = "mainsite/send_sms.html"

    model = SmsGroupMessage
    # fields = ["recipients", "body"]
    form_class = SendSmsForm

    def get_success_url(self):
        return reverse(
            "mainsite:prev_sms_status_details", kwargs={"pk": self.object.pk}
        )

    def form_valid(self, form):
        self.object = form.save()
        self.object.instanciate()
        self.object.send_all()
        return HttpResponseRedirect(self.get_success_url())


class SmsResendView(IsStaffMixin, SingleObjectMixin, RedirectView):
    model = SmsGroupMessage
    http_method_names = ["post"]

    def get_redirect_url(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.send_all()
        return reverse(
            "mainsite:prev_sms_status_details", kwargs={"pk": self.object.pk}
        )


class ReassignDevicesView(IsStaffMixin, RedirectView):
    http_method_names = ["post"]

    @staticmethod
    def round_robin(l_a, l_b):
        """ Iterates over the elements of a, with elements of b in a round-robin
        fashion.
        Eg. if l_a = [1, 2, 3, 4, 5], l_b = [1, 2], this will yield
        [(1,1), (2,2), (3,1), (4,2), (5,1)].
        """
        for (a, b) in itertools.zip_longest(l_a, itertools.cycle(l_b)):
            if a:  # After iterating over l_a, a will be None
                yield (a, b)
            else:
                break

    def get_redirect_url(self, *args, **kwargs):
        recipients = SmsRecipient.objects.all()
        devices = SmsDevice.objects.all()
        devices = list(filter(lambda x: x.is_available(), devices))
        if not devices:
            messages.error(
                self.request,
                (
                    "Impossible de réassigner les destinataires : "
                    + "aucun téléphone d'envoi disponible actuellement."
                ),
            )
        else:
            for (recipient, device) in self.round_robin(recipients, devices):
                recipient.last_sms_device = device
                recipient.save()
        return reverse("mainsite:devices_status")


class PreviousSmsDetailsView(IsStaffMixin, DetailView):
    model = SmsGroupMessage
    template_name = "mainsite/previous_sms_details.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["group_message"] = self.object
        context["individual_messages"] = self.object.individual_messages.all()
        return context


class PreviousSmsListView(IsStaffMixin, ListView):
    model = SmsGroupMessage
    template_name = "mainsite/previous_sms_list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related("individual_messages").annotate(
            max_date=Max("individual_messages__sent_date")
        )


class DevicesStatusView(IsStaffMixin, TemplateView):
    template_name = "mainsite/devices_status.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["devices"] = SmsDevice.objects.all().prefetch_related(
            "smsrecipient_set"
        )
        return context

mainsite/templates/mainsite/devices_status.html
{% extends "base.html" %}

{% block pagename %}État des téléphones d'envoi{% endblock %}

{% block content %}

<form method="POST" action="{% url "mainsite:reassign_devices" %}"
                    class="reassign_devices_form action_button_form">
  {% csrf_token %}
  <input
    type="submit"
    class="button action_button reassign_devices_button"
    value="Refaire la répartition des destinataires" />
</form>

<table class="devices_status_table">
  <tr>
    <th>Téléphone</th>
    <th>État</th>
    <th>Destinataires associés</th>
  </tr>
{% for device in devices %}
  <tr>
    <td>{{ device.device_name }}</td>
    <td class="dev_{% if not device.is_available %}un{% endif %}available">
      {% if device.is_available %}UP{% else %}DOWN{% endif %}
    </td>
    <td>{{ device.smsrecipient_set.count }}</td>
  </tr>
{% endfor %}
</table>
{% endblock %}

mainsite/templates/mainsite/home.html
{% extends "base.html" %}

{% block pagename %}Accueil{% endblock %}

{% block content %}
<div class="home_stats">
  <div>
    <div class="stat_figure">{{ sms_sent }}</div>
    <div class="stat_label">SMS envoyés</div>
  </div>

  <div>
    <div class="stat_figure">{{ sms_errors }}</div>
    <div class="stat_label">SMS en erreur</div>
  </div>
</div>
{% endblock %}

mainsite/templates/mainsite/previous_sms_details.html
{% extends "base.html" %}

{% block pagename %}SMS envoyé{% endblock %}

{% block content %}
<p>Le SMS a été envoyé au groupe <b>{{ group_message.recipients }}</b>.</p>

{% if object.can_resend %}
<form method="POST" action="{% url "mainsite:sms_resend" object.pk %}"
                    class="resend_form action_button_form">
  {% csrf_token %}
  <input
    type="submit"
    class="button action_button resend_button"
    value="Renvoyer les messages en erreur" />
</form>
{% endif %}

<table class="group_sms_send_status">
  <tr>
    <th>Destinataire</th>
    <th>État</th>
    <th>Depuis</th>
  </tr>
  {% for message in individual_messages %}
  <tr>
    <td>{{ message.recipient }}</td>
    <td class="msg_status_{{ message.sent_status}}">{{ message.sent_status_text }}</td>
    <td>{{ message.sent_date|date:"H:i:s" }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

mainsite/templates/mainsite/previous_sms_list.html
{% extends "base.html" %}

{% block pagename %}État des messages précédents{% endblock %}

{% block content %}
<table class="sent_messages_status_table">
  <tr>
    <th>Pour</th>
    <th>Message</th>
    <th>État</th>
    <th>Heure</th>
    <th>Détails</th>
  </tr>
{% for msg in object_list %}
  <tr>
    <td>{{ msg.recipients.name }}</td>
    <td>{{ msg.body|truncatewords:20 }}</td>
    <td class="msg_status_{{ msg.group_proeminent_status }}">
      {{ msg.group_proeminent_status_text }}
    </td>
    <td>{{ msg.max_date|date:'H:i:s' }}</td>
    <td>
      <a href="{% url "mainsite:prev_sms_status_details" msg.pk %}">Détails</a>
    </td>
  </tr>
{% endfor %}
</table>
{% endblock %}

mainsite/templates/mainsite/send_sms.html
{% extends "base.html" %}

{% block pagename %}Envoi de SMS{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <input type="submit" value="Save">
</form>
{% endblock %}